### ISSUE TITLE
Extending Item class to add more properties

### ISSUE THREAD

**Issue by GhaziTriki** [samvaughton/omnipay-barclays-epdq#10]
This API offers more properties that can describe an Item :

ITEMATTRIBUTES**XX**
ITEMCATEGORY**XX**
ITEMCOMMENTS**XX**
ITEMDESC**XX**
ITEMDISCOUNT**XX**
ITEMFDMPRODUCTCATEG**XX**
ITEMID**XX**
ITEMNAME**XX**
ITEMPRICE**XX**
ITEMQUANT**XX**
ITEMQUANTORIG**XX**
ITEMUNITOFMEASURE**XX**
ITEMVAT**XX**
ITEMVATCODE**XX**
ITEMWEIGHT**XX**

I will create a pull request to add the those parameters.

How Item class should be extended? As we have now a specific need and we need to stay Omnipay compliant. Any suggestion?

**Comment by coatesap** [comment]
@GhaziTriki - It might be worth having a look at some of the other Omnipay drivers, as I'm sure there are probably quite a few that implement passing of item/cart information through to the gateway...

**Comment by GhaziTriki** [comment]
I have taken a look at them all I haven't found any custom implementation of Item class. I will take a deeper look.

**Comment by GhaziTriki** [comment]
A pull request almost ready. I need a clarification about 3 parameters from Barclays and I will be able to push and be ready to release a new version.
